Abstracted Everything
ACat701/SuperSwerve23 pull request #1
Opened 2023-12-17 01:51 UTC by ACat701

2023-12-17 08:28 UTC, GalexY727 requested changes

2023-12-17 08:28 UTC, GalexY727 commented on src/main/java/frc/robot/SwerveConstants.java
> +    public static final SwerveConstants MK4I_L2 = new SwerveConstants(150.0 / 7.0, 0.30322652292, 6.75, 16.5);
Units.feetToMeters(16.5)

2023-12-17 08:28 UTC, GalexY727 commented on src/main/java/frc/robot/SwerveConstants.java
> +    public static final SwerveConstants MK4I_L1 = new SwerveConstants(150.0 / 7.0, 0.30322652292, 8.14, 13.7);
Units.feetToMeters(13.7)

2023-12-17 08:28 UTC, GalexY727 commented on src/main/java/frc/robot/SwerveConstants.java
> +    public static final SwerveConstants MK4I_L3 = new SwerveConstants(150.0 / 7.0, 0.30322652292, 6.12, 18.2);
ok you get the jist

2023-12-17 08:28 UTC, GalexY727 commented on src/main/java/frc/robot/SwerveConstants.java
> +    public static final SwerveConstants MK4I_L1_FOC = new SwerveConstants(150.0 / 7.0, 0.30322652292, 8.14, 13.0);
but i'm not going away

2023-12-17 08:28 UTC, GalexY727 commented on src/main/java/frc/robot/SwerveConstants.java
> +    public static final SwerveConstants MK4I_L2_FOC = new SwerveConstants(150.0 / 7.0, 0.30322652292, 6.75, 15.7);
never

2023-12-17 08:28 UTC, GalexY727 commented on src/main/java/frc/robot/SwerveConstants.java
> +    public static final SwerveConstants MK4I_L3_FOC = new SwerveConstants(150.0 / 7.0, 0.30322652292, 6.12, 17.3);
ever
okay have a nice day

2023-12-18 19:05 UTC, ACat701 commented
Tested :) it workey

2023-12-18 19:05 UTC, merged